version: 2

references:
  container_config: &container_config
    docker:
      - image: electronuserland/builder:wine-chrome-05.21
        environment:
          TARGET_ARCH: x64
    working_directory: ~/neon-wallet

  win_config: &win_config
    docker:
      - image: electronuserland/builder:wine
        environment:
          TARGET_ARCH: x64
    working_directory: ~/neon-wallet

  workspace_root: &workspace_root ~/neon-wallet

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: neon-wallet-dependencies-cache-{{ checksum "yarn.lock" }}
      - run: apt-get -y update
      - run: apt-get -y install libusb-1.0-0-dev icnsutils graphicsmagick libudev-dev
      - run: yarn config delete proxy
      - run: yarn install --ignore-engines --frozen-lockfile --network-timeout 1000000 --network-concurrency 1
      - run: yarn lint
      - run: yarn flow
      - run: yarn assets
      - save_cache:
          key: neon-wallet-dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - /usr/local/share/.cache/yarn/v2
            - ./node_modules

  deploy_win64:
    <<: *win_config
    steps:
      - checkout
      - restore_cache:
          key: neon-wallet-dependencies-cache-{{ checksum "yarn.lock" }}
      - run: apt-get -y update
      - run: apt-get -y install libusb-1.0-0-dev icnsutils graphicsmagick libudev-dev
      - run: apt-get install --no-install-recommends -y gcc-multilib g++-multilib
      - run: yarn install --ignore-engines --frozen-lockfile --network-timeout 1000000 --network-concurrency 1
      - run: yarn assets
      - run: yarn electron-builder -w --x64
      - store_artifacts:
          path: dist
          destination: build

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - deploy_win64
